services:
  minio:
    image: minio/minio:latest
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_REGION: dummy-region
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DOMAIN: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    networks:
      local-iceberg-lakehouse:
        aliases:
          - warehouse.minio
    command: ["server", "/data", "--console-address", ":9001"]

  minio-client:
    image: minio/mc:latest
    depends_on:
      - minio
    networks:
      - local-iceberg-lakehouse
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_REGION: dummy-region
      AWS_BUCKET: ${AWS_BUCKET}
    entrypoint: >
      /bin/sh -c "
      until (mc alias set minio http://minio:9000 $$AWS_ACCESS_KEY_ID $$AWS_SECRET_ACCESS_KEY) do echo '...waiting...' && sleep 1; done;
      mc rm -r --force minio/$$AWS_BUCKET;
      mc mb minio/$$AWS_BUCKET;
      mc anonymous set public minio/$$AWS_BUCKET;
      tail -f /dev/null
      " 

  nessie-catalog:
    image: projectnessie/nessie:0.76.6
    networks:
      - local-iceberg-lakehouse
    ports:
      - "19120:19120"

  trino:
    image: trinodb/trino:latest
    networks:
      - local-iceberg-lakehouse
    ports:
      - "8080:8080"
    environment:
      TRINO_JVM_OPTS: -Xmx2G
      CLIENT_ID: ${ROOT_CLIENT_ID:-admin}
      CLIENT_SECRET: ${ROOT_CLIENT_SECRET:-admin}
    volumes:
      - ./trino/config/catalog:/etc/trino/catalog

networks:
  local-iceberg-lakehouse:
    name: local-iceberg-lakehouse