services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./minio_data:/data
    networks:
      local-iceberg-lakehouse:
        aliases:
          - warehouse.minio
    command: ["server", "/data", "--console-address", ":9001"]

  minio-client:
    image: minio/mc:latest
    depends_on:
      - minio
    networks:
      - local-iceberg-lakehouse
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_BUCKET: ${AWS_BUCKET}
    entrypoint: >
      /bin/sh -c "
      until (mc alias set minio http://minio:9000 $$AWS_ACCESS_KEY_ID $$AWS_SECRET_ACCESS_KEY) do echo '...waiting...' && sleep 1; done;
      mc rm -r --force minio/$$AWS_BUCKET;
      mc mb minio/$$AWS_BUCKET;
      mc anonymous set public minio/$$AWS_BUCKET;
      tail -f /dev/null
      " 

  polaris:
    image: apache/polaris:latest
    platform: linux/amd64
    ports:
      - "8181:8181"
      - "8182:8182"
      - "5005:5005"
    networks:
      - local-iceberg-lakehouse
    environment:
      JAVA_DEBUG: true
      JAVA_DEBUG_PORT: "*:5005"
      POLARIS_PERSISTENCE_TYPE: relational-jdbc
      POLARIS_PERSISTENCE_RELATIONAL_JDBC_MAX_RETRIES: 5
      POLARIS_PERSISTENCE_RELATIONAL_JDBC_INITIAL_DELAY_IN_MS: 100
      POLARIS_PERSISTENCE_RELATIONAL_JDBC_MAX_DURATION_IN_MS: 5000
      QUARKUS_DATASOURCE_JDBC_URL: $QUARKUS_DATASOURCE_JDBC_URL
      QUARKUS_DATASOURCE_USERNAME: $QUARKUS_DATASOURCE_USERNAME
      QUARKUS_DATASOURCE_PASSWORD: $QUARKUS_DATASOURCE_PASSWORD
      QUARKUS_OTEL_SDK_DISABLED: true

      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_ENDPOINT_URL_S3: http://minio:9000
      AWS_ENDPOINT_URL_STS: http://minio:9000

      POLARIS_REALM_CONTEXT_REALMS: POLARIS
      POLARIS_BOOTSTRAP_CREDENTIALS: POLARIS,${ROOT_CLIENT_ID:-admin},${ROOT_CLIENT_SECRET:-admin}
      polaris.features.DROP_WITH_PURGE_ENABLED: true # allow dropping tables from the SQL client
      polaris.features."ALLOW_INSECURE_STORAGE_TYPES": "true"
      polaris.features."SUPPORTED_CATALOG_STORAGE_TYPES": "[\"FILE\",\"S3\"]"
      polaris.readiness.ignore-severe-issues: "true"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8181/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  trino:
    image: trinodb/trino:latest
    networks:
      - local-iceberg-lakehouse
    ports:
      - "8080:8080"
    environment:
      TRINO_JVM_OPTS: -Xmx2G
      CLIENT_ID: ${ROOT_CLIENT_ID:-admin}
      CLIENT_SECRET: ${ROOT_CLIENT_SECRET:-admin}
    volumes:
      - ./trino/config/catalog:/etc/trino/catalog

  polaris-console:
    image: pdaniil136/polaris-console
    networks:
      - local-iceberg-lakehouse
    depends_on:
      polaris:
        condition: service_healthy
    ports:
      - "8081:80"
    environment:
      - VITE_POLARIS_API_URL=http://polaris:8181
      - VITE_POLARIS_REALM=POLARIS


networks:
  local-iceberg-lakehouse:
    name: local-iceberg-lakehouse