services:
  polaris:
    image: apache/polaris:latest
    platform: linux/amd64
    container_name: polaris
    ports:
      - "8181:8181"
      - "8182:8182"
      - "5005:5005"
    networks:
      - local-iceberg-lakehouse
    environment:
      JAVA_DEBUG: true
      JAVA_DEBUG_PORT: "*:5005"
      POLARIS_PERSISTENCE_TYPE: relational-jdbc
      POLARIS_PERSISTENCE_RELATIONAL_JDBC_MAX_RETRIES: 5
      POLARIS_PERSISTENCE_RELATIONAL_JDBC_INITIAL_DELAY_IN_MS: 100
      POLARIS_PERSISTENCE_RELATIONAL_JDBC_MAX_DURATION_IN_MS: 5000
      QUARKUS_DATASOURCE_JDBC_URL: $QUARKUS_DATASOURCE_JDBC_URL
      QUARKUS_DATASOURCE_USERNAME: $QUARKUS_DATASOURCE_USERNAME
      QUARKUS_DATASOURCE_PASSWORD: $QUARKUS_DATASOURCE_PASSWORD
      QUARKUS_OTEL_SDK_DISABLED: true

      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_ENDPOINT_URL_S3: http://minio:9000
      AWS_ENDPOINT_URL_STS: http://minio:9000

      POLARIS_REALM_CONTEXT_REALMS: POLARIS
      POLARIS_BOOTSTRAP_CREDENTIALS: POLARIS,${POLARIS_USERNAME},${POLARIS_PASSWORD}
      polaris.features.DROP_WITH_PURGE_ENABLED: true # allow dropping tables from the SQL client
      polaris.features."ALLOW_INSECURE_STORAGE_TYPES": "true"
      polaris.features."SUPPORTED_CATALOG_STORAGE_TYPES": "[\"FILE\",\"S3\"]"
      polaris.readiness.ignore-severe-issues: "true"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8181/healthcheck"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 60s

  polaris-console:
    image: pdaniil136/polaris-console:0.0.2
    container_name: polaris_console
    depends_on:
      polaris:
        condition: service_healthy
    ports:
      - "8081:80"
    networks:
      - local-iceberg-lakehouse
    environment:
      - VITE_POLARIS_API_URL=http://polaris:8181
      - VITE_POLARIS_REALM=POLARIS

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_REGION_NAME: us-east-1
      MINIO_REGION: us-east-1
      MINIO_DOMAIN: minio
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - local-iceberg-lakehouse
    # volumes:
    #   - ./minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5;
      mc alias set minio http://localhost:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb minio/${MINIO_BUCKET};
      tail -f /dev/null"

networks:
  local-iceberg-lakehouse:
    name: local-iceberg-lakehouse